# Generated by Django 2.1.1 on 2018-09-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20180914_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori'},
        ),
    ]
