# Generated by Django 2.1.2 on 2018-10-08 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produk', '0003_auto_20180914_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongkosKirim', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alamat', models.TextField(blank=True)),
                ('Date', models.DateField(auto_now=True)),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
