# Generated by Django 2.1.2 on 2018-10-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_auto_20181008_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('checkout', 'Checkout'), ('paid', 'Paid'), ('delivered', 'Delivered')], max_length=15, null=True),
        ),
    ]
