# Generated by Django 2.1.2 on 2018-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ongkosKirim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
