# Generated by Django 2.1.2 on 2018-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_auto_20181008_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
