# Generated by Django 2.1.2 on 2018-10-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0008_auto_20181008_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Terbayar'), ('delivered', 'Terkirim')], default='checkout', max_length=15),
        ),
    ]
