# Generated by Django 2.1.2 on 2018-10-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0009_auto_20181008_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Order Detail',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='order',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Order'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.Produk'),
        ),
    ]
