# Generated by Django 2.1.2 on 2018-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0010_auto_20181008_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.TextField(default='Jogja'),
        ),
        migrations.AddField(
            model_name='order',
            name='no_hape',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
