# Generated by Django 2.1.2 on 2018-10-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0012_auto_20181024_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_detail',
            unique_together={('order', 'produk')},
        ),
    ]
