# Generated by Django 2.1.2 on 2018-10-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0013_auto_20181029_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_order', to='produk.Order'),
        ),
    ]
