# Generated by Django 2.1.2 on 2018-10-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0014_auto_20181029_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='sub_total',
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_order', to='produk.Produk'),
        ),
    ]
